<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>ERP</title>
</head>
<body>
<h1>ERP</h1><hr>
<h2>Управление производством</h2>
<hr>
<ul>
    <li><a href="/plan">План производства</a></li>
    <li><a href="/workshop/zagotovka">Заготовка</a></li>
    <li><a href="/workshop/mexobrabotka">Мехобработка</a></li>
    <li><a href="/workshop/svarka">Сварка</a></li>
    <li><a href="/workshop/sborka">Сборка</a></li>
    <li><a href="/workshop/outsourcing">Аутсорсинг</a></li>
</ul>
</body>
</html>